### ISSUE TITLE
Not really an issue, just wanted to learn a bit about reversed data...

### ISSUE THREAD

**Issue by guycalledfrank** [Greavesy1899/MafiaToolkit#101]
Hi Greavesy! It's a great project you have here :)
I couldn't find a way to contact you anywhere else, so I'm writing it here.

I was interested in finding how Mafia 2 blends car sounds, so I used the Toolkit to open and check EntityDataStorages of particular cars and found a lot of useful parameters. I realized the files themselves don't store parameter names anywhere - they're all coming from your own classes: https://github.com/Greavesy1899/MafiaToolkit/blob/9b803255212c470487bb8e94abffa5edd319ac1e/Mafia2Libs/ResourceTypes/FileTypes/Actors/Types/ActorCar.cs#L76

That got me wondering... how did you figure out what property does what? Did someone reverse and document it before? I'm especially interested in figuring out how the engine audio system works - it looks very simple on a first glance (fading/pitching/overlapping loops), but it's very tricky in practice.
For example, if we assume that RotLo and RotHi are normalized (0-100) values mapping to (0-RotationsMax or RotationsMin-RotationsMax), and the volume is changing from RotLoVol to RotHiVal in this range... if we just leave that, there will be abrupt volume changes, because sometimes RotLoVol is already 90... or does it mean that all sounds are playing always and the Lo/Hi Vol is just clamped beyond Lo/Hi? I can assume the volume is then not set directly based on RPM, but instead is constantly getting interpolated towards the target value... using FadeTime/EnvelopeRot parameters?
If you figured out this fading system, can you share how it works? :)

**Comment by Greavesy1899** [comment]
I just used the games executable to figure out the names of the properties. This type of format in particular (shared with Actors) associates a point in memory with a name, so most of what you see is taken from that. Other than my work, no one has ever reverse engineered or documented the format or the Car Audio system
