### ISSUE TITLE
Mafia 1: DE tables\ingame.sds\config\human2config.xml does not convert correctly

### ISSUE THREAD

**Issue by LukeRoss00** [Greavesy1899/MafiaToolkit#43]
I have Mafia 1: DE from the Epic Games Store, unmodded and updated to the current version. When unpacking tables\ingame.sds, no errors are reported by the tool, but tables\extracted\ingame.sds\config\human2config.xml remains in a binary format. The other .xml files in the same directory are converted correctly. I'm attaching a zip archive containing the problematic file, together with another converted file from the same folder to show that the problem is limited to human2config.xml.

[config.zip](https://github.com/Greavesy1899/MafiaToolkit/files/7072105/config.zip)

The problem occurs identically with version 2.21 and 2.13 of the toolkit.

**Comment by LukeRoss00** [comment]
Thanks for getting back to me! I imagined that it was a problem with the XML decompiler, but reported it anyway because I saw that some mods mention editing human2config.xml specifically, with line numbers and everything, so at least at some point in the past the file would decompile correctly. Probably it was later changed by the developers in recent game versions.

**Comment by Greavesy1899** [comment]
I think there is another 'resource explorer' tool which may edit this file. I personally decided to avoid decompiling any XMLs which included the 'xml namespace' content to avoid unexpected problems such as recompiling problems (mainly just avoiding game problems too.)

**Comment by LukeRoss00** [comment]
Makes sense, thanks!
