### ISSUE TITLE
.NET 5.0 Runtime can no longer be downloaded.

### ISSUE THREAD

**Issue by CombineSlayer24** [Greavesy1899/MafiaToolkit#76]
**Describe the bug**
I cannot run the application due to .NET 5.0 no longer being downloadable.

**Expected behavior**
When I try to launch MafiaToolkit.exe, a popup will appear "To run this application, you must Install .NET. Would you like to install it?"
I pressed yes and I'm greeted with this screen (Shown down below in Screenshots)

**Screenshots**
![image](https://user-images.githubusercontent.com/82725572/178880192-1690b9b7-39b3-440a-a7e8-fd2bcb792d2c.png)

![image](https://user-images.githubusercontent.com/82725572/178878682-2ff0b776-3a3c-4237-92c5-529893c6c893.png)

**Desktop (please complete the following information):**
 - OS: [ Windows 10 Home]
 - Browser [ Microsoft Edge ]
 - Version [ I don't quite understand this, 10 Home?  ]

**Additional context**
I wanted to extract the Policeman sounds for something, but I cannot access the toolkit since NET 5.0 is retired.

**Comment by Greavesy1899** [comment]
Link is here https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x86-installer

That message box is Microsoft's doing, it appears to be misleading

**Comment by Wdestroier** [comment]
@szymonuwu I only had to install the latter on Windows 11 x86_64/amd64. @Greavesy1899 Would be nice to have these download links in a required dependencies section in the README.

**Comment by CombineSlayer24** [comment]
> Link is here https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x86-installer
> 
> That message box is Microsoft's doing, it appears to be misleading

Ah, not sure why Microsoft mislead me.
