### ISSUE TITLE
Discord Link

### ISSUE THREAD

**Issue by p1ggsy** [Greavesy1899/MafiaToolkit#81]
Dead link to discord server
[![2023-04-19-10_33_03-Discord--Opera--KOPY.md.png](https://i.ibb.co/QC6k8nd/2023-04-19-10-33-03-Discord-Opera.png)](https://i.ibb.co/QC6k8nd/2023-04-19-10-33-03-Discord-Opera.png)

**Comment by Greavesy1899** [comment]
Cheers, fixed the link
