### ISSUE TITLE
Localize

### ISSUE THREAD

**Issue by MohammedXD29** [Greavesy1899/MafiaToolkit#82]
Hi, I'm trying to translate Mafia DE to Arabic and I extracted sds to xml and translated the file but when I click import it shows me an error "Object reference not set to an instance of an object" but if I import the original XML it will import without any problem, so what I have to do?
Sorry for bad English, I think.

**Comment by Greavesy1899** [comment]
Need more information - which SDS are you trying to edit? Is this an XBin file, or something different?

**Comment by MohammedXD29** [comment]
> Need more information - which SDS are you trying to edit? Is this an XBin file, or something different?

Yes, it's XBin file name is "Stringtable_en_common_group.XBin"

**Comment by Greavesy1899** [comment]
Can you please send me the file you are attempting to import into the Xbin editor?

**Comment by MohammedXD29** [comment]
https://www.mediafire.com/file/hxpdcuktol59rcl/stringtable_en_common_group.xml/file

**Comment by Greavesy1899** [comment]
Your XML appears to be using the old format, which is no longer supported. You need to export a new XML using version 2.28.

**Comment by MohammedXD29** [comment]
I will try with the old version

**Comment by Greavesy1899** [comment]
Please use 2.28 and re-export the XML

**Comment by MohammedXD29** [comment]
What about the translated strings?

**Comment by MohammedXD29** [comment]
OK, thank you so much.

**Comment by MohammedXD29** [comment]
It did'nt work, I copied the codes from the new one to the old and it did'nt work, I tried to fix it but i fail

Here's the file :
[stringtable_en_common_group.txt](https://github.com/Greavesy1899/MafiaToolkit/files/11611315/stringtable_en_common_group.txt)
just change it to XML.

**Comment by Greavesy1899** [comment]
You have broken the XML format. Just change the element "Content" and nothing else. Do you change any "LocalisableString" eleemnts.

**Comment by MohammedXD29** [comment]
Wich content you mean? this </content> or this <content>? and change it to what?

**Comment by Greavesy1899** [comment]
![image](https://github.com/Greavesy1899/MafiaToolkit/assets/26023883/7857dfee-0929-4f73-8563-77f2e89fff0c)

You only need to edit these lines. You do not need to edit LocalisableString

**Comment by MohammedXD29** [comment]
OK, you mean to delete / ? or what.

**Comment by Greavesy1899** [comment]
You have to make sure that the LocalisableString is in exactly the same format as above. If it as a "/" at the end, then remove it.

**Comment by MohammedXD29** [comment]
But / is in the start in content and LocalisableString

**Comment by MohammedXD29** [comment]
Can you do it for me?

**Comment by Greavesy1899** [comment]
What do you want me to do?

**Comment by MohammedXD29** [comment]
import the file 😅

**Comment by Greavesy1899** [comment]
I can provide you an example, but i'm not doing it for you

**Comment by MohammedXD29** [comment]
OK

**Comment by MohammedXD29** [comment]
So now what I have to do?

**Comment by Greavesy1899** [comment]
The XML entries should look like this. Look very carefully.
```xml
<LocalisableString StringID="63039103238888">
      <Content Type="String">؟ﻦﺤﻧ ﺍﺬﻫ ﻥﺎﻛ ﻞﻫ</Content>
</LocalisableString>
```

This is wrong:
```xml
<LocalisableString StringID="63039103238888" Name="0" />
      <Content Type="String">؟ﻦﺤﻧ ﺍﺬﻫ ﻥﺎﻛ ﻞﻫ</Content>
</LocalisableString>
```
It's wrong because:
1. The name attribute in LocalisableString is not required and will crash MafiaToolkit.
2. The slash at the end of LocalisableString is not required because the element ends after `<Content Type="String">؟ﻦﺤﻧ ﺍﺬﻫ ﻥﺎﻛ ﻞﻫ</Content>` LocalisableString should wrap the <Content> element.

**Comment by Greavesy1899** [comment]
Do you mean the missing indentations? That can be solved on your end. Both images look fine to me.

**Comment by MohammedXD29** [comment]
OK

**Comment by Greavesy1899** [comment]
Can you show me a picture of the XML and editor

**Comment by Kamzik123** [comment]
Did you repack the sds?

**Comment by MohammedXD29** [comment]
> Did you repack the sds?

No

**Comment by MohammedXD29** [comment]
> Can you show me a picture of the XML and editor

You mean the XML file and mafia toolkit?

**Comment by MohammedXD29** [comment]
> Did you repack the sds?

I exported it after I imported it and it's the same

**Comment by Kamzik123** [comment]
Repack it after you edit the xbin...

**Comment by MohammedXD29** [comment]
OK

**Comment by MohammedXD29** [comment]
It worked without repack, the translated strings is not of the ones in mafia toolkit, Thank You.

**Comment by MohammedXD29** [comment]
I translated some strings now and then import, it has been changed but the other ones didn't.

**Comment by Greavesy1899** [comment]
Did you use the same XML when translating the other strings?

**Comment by MohammedXD29** [comment]
> Did you use the same XML when translating the other strings?

I noticed right now it wasn't the same 🤕

**Comment by Greavesy1899** [comment]
You don't have to export once you have made the changes. You can reuse the same XML.

**Comment by MohammedXD29** [comment]
😅 😅 😅 😅 😅

**Comment by MohammedXD29** [comment]
[stringtable_en_common_group.txt](https://github.com/Greavesy1899/MafiaToolkit/files/11614589/stringtable_en_common_group.txt)

**Comment by Greavesy1899** [comment]
![image](https://github.com/Greavesy1899/MafiaToolkit/assets/26023883/2ef86968-8723-412f-a250-8b367e23e513)

Broken on line 1771.

**Comment by Greavesy1899** [comment]
> The XML entries should look like this. Look very carefully.
> 
> ```
> <LocalisableString StringID="63039103238888">
>       <Content Type="String">؟ﻦﺤﻧ ﺍﺬﻫ ﻥﺎﻛ ﻞﻫ</Content>
> </LocalisableString>
> ```
> 
> This is wrong:
> 
> ```
> <LocalisableString StringID="63039103238888" Name="0" />
>       <Content Type="String">؟ﻦﺤﻧ ﺍﺬﻫ ﻥﺎﻛ ﻞﻫ</Content>
> </LocalisableString>
> ```
> 
> It's wrong because:
> 
>     1. The name attribute in LocalisableString is not required and will crash MafiaToolkit, so it should be removed.
> 
>     2. The slash at the end of LocalisableString is not required because the element ends after `<Content Type="String">؟ﻦﺤﻧ ﺍﺬﻫ ﻥﺎﻛ ﻞﻫ</Content>` LocalisableString should wrap the  element.

Exactly the same issue as this.

**Comment by MohammedXD29** [comment]
Can you please fix it for me? 🙏

**Comment by Greavesy1899** [comment]
This is a really obvious fix. Please study very carefully, so you can fix it yourself in the future.
```xml
    <LocalisableString StringID="405500523941933717">
      <Content Type="String">Desk Guard</Content>
    </LocalisableString>
```
See that i've simply removed the end part of the LocalisableString element. I am close to closing this issue, because I believe this to be user error rather than toolkit error.

**Comment by MohammedXD29** [comment]
Thank you so much, I fixed it.
