### ISSUE TITLE
Can't pack "tables.sds" "Expected the version in the table file to be the same as the entry in SDSContent.xml"

### ISSUE THREAD

**Issue by CognizantDoor** [Greavesy1899/MafiaToolkit#83]
After i overwrited some files, i tried to pack "tables.sds", but i can't, because of this error "Expected the version in the table file to be the same as the entry in SDSContent.xml". I tried everything to fix it, but none of these methods worked. Hope you gonna fix it next time. Love ya, See ya. 
![Zrzut ekranu 2023-08-15 230517](https://github.com/Greavesy1899/MafiaToolkit/assets/142354060/3256f5b1-54f7-4b61-9d0c-a008ccfe8900)

**Comment by Greavesy1899** [comment]
Was this copied between M2DE and M2 classic? If so, it will cause an issue

**Comment by szymonuwu** [comment]
SDSContent.xml file:

<Version>X</Version>

Where X stands for:
1 = Mafia 2 (Classic)
2 = Mafia 2 Definitive Edition

**Comment by Greavesy1899** [comment]
Resolved on reddit. Need to make tables backwards compatible as this [commit](https://github.com/Greavesy1899/MafiaToolkit/commit/814c6f363c7b5c9211a7eaa1e6f33dfc6ed84079) broke it
